trigger:
  - master
  - develop

jobs:
  - job: setup_env
    displayName: "Setup"
    strategy:
      matrix:
        Ubuntu20:
          AGENT_NAME: "rmm-ubu20"

    pool:
      name: linux-vms
      demands:
        - agent.name -equals $(AGENT_NAME)

    steps:
      - script: |
          sudo -u postgres psql -c 'DROP DATABASE IF EXISTS pipeline'
          sudo -u postgres psql -c 'DROP DATABASE IF EXISTS test_pipeline'
          sudo -u postgres psql -c 'CREATE DATABASE pipeline'

          rm -rf /myagent/_work/1/s/api/env
          cd /myagent/_work/1/s/api
          python3 -m venv env
          source env/bin/activate
          cd /myagent/_work/1/s/api/tacticalrmm
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir setuptools==50.3.2 wheel==0.36.1
          pip install --no-cache-dir -r requirements.txt -r requirements-test.txt
        displayName: "Install Python Dependencies"

      - script: |
          cd /myagent/_work/1/s/api
          source env/bin/activate
          cd /myagent/_work/1/s/api/tacticalrmm
          coverage run manage.py test -v 2
          if [ $? -ne 0 ]; then
              exit 1
          fi
        displayName: "Run django tests"

      - script: |
          pip install coveralls
          export CIRCLE_BRANCH=$BUILD_SOURCEBRANCH
          coveralls
        displayName: "coveralls"
        env:
          CIRCLECI: 1
          CIRCLE_BUILD_NUM: $(Build.BuildNumber)
