trigger:
  - master
  - develop

jobs:
  - job: setup_env
    displayName: "Setup"
    strategy:
      matrix:
        Ubuntu20:
          AGENT_NAME: "rmm-ubu20"

    pool:
      name: linux-vms
      demands:
        - agent.name -equals $(AGENT_NAME)

    steps:
      - script: |
          sudo -u postgres psql -c 'DROP DATABASE IF EXISTS pipeline'
          sudo -u postgres psql -c 'DROP DATABASE IF EXISTS test_pipeline'
          sudo -u postgres psql -c 'CREATE DATABASE pipeline'

          rm -rf /myagent/_work/1/s/api/env
          cd /myagent/_work/1/s/api
          python3 -m venv env
          source env/bin/activate
          cd /myagent/_work/1/s/api/tacticalrmm
          pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir setuptools==50.3.2 wheel==0.36.1
          pip install --no-cache-dir -r requirements.txt -r requirements-test.txt
        displayName: "Install Python Dependencies"

      - script: |
          cd /myagent/_work/1/s/api
          git config user.email "admin@example.com"
          git config user.name "Bob"
          git fetch
          git checkout develop
          git pull
          source env/bin/activate
          cd /myagent/_work/1/s/api/tacticalrmm
          coverage run manage.py test -v 2
          coveralls
        displayName: "Run django tests"
        failOnStderr: "true"
