site_name: "Tactical RMM Documentation"
nav:
  - Home: index.md
  - Sponsor: sponsor.md
  - Code Signing: code_signing.md
  - RMM Installation:
      - "Traditional Install": install_server.md
      - "Docker Install": install_docker.md
  - Agent Installation: install_agent.md
  - Updating:
      - "Updating the RMM": update_server.md
      - "Updating the RMM (Docker)": update_docker.md
      - "Updating Agents": update_agents.md
  - Functionality:
      - "Alerting": functions/alerting.md
      - "API Access": functions/api.md
      - "Automated Tasks": functions/automated_tasks.md
      - "Custom Fields": functions/custom_fields.md
      - "Database Maintenance": functions/database_maintenance.md
      - "Django Admin": functions/django_admin.md
      - "Global Keystore": functions/keystore.md
      - "Maintenance Mode": functions/maintenance_mode.md
      - "Remote Background": functions/remote_bg.md
      - "Settings Override": functions/settings_override.md
      - "Scripting": functions/scripting.md
      - "URL Actions": functions/url_actions.md
      - "User Interface Preferences": functions/user_ui.md
      - "Examples": functions/examples.md
  - Backup: backup.md
  - Restore: restore.md
  - Troubleshooting: troubleshooting.md
  - FAQ: faq.md
  - Management Commands: management_cmds.md
  - MeshCentral Integration: mesh_integration.md
  - 3rd Party Integrations:
      - "Grafana": 3rdparty_grafana.md
      - "AnyDesk": 3rdparty_anydesk.md
      - "Connectwise Control / Screenconnect": 3rdparty_screenconnect.md
      - "TeamViewer": 3rdparty_teamviewer.md
      - "BitDefender GravityZone": 3rdparty_bitdefender_gravityzone.md
  - Unsupported Extras:
      - "Unsupported Guidelines": unsupported_guidelines.md
      - "Unsupported Scripts": unsupported_scripts.md
      - "Securing nginx": securing_nginx.md
      - "Installing in Synology docker": unsupported_synology_docker_install.md
  - Tips n' Tricks: tipsntricks.md
  - Contributing:
      - "Contributing to Docs": contributing.md
      - "Contributing to Community Scripts": contributing_community_scripts.md
      - "Contributing using VSCode": contributing_using_vscode.md
      - "Contributing using Docker": contributing_using_docker.md
      - "Contributing using a Remote Server": contributing_using_a_remote_server.md
  - License: license.md
site_description: "A remote monitoring and management tool"
site_author: "wh1te909"
site_url: "https://wh1te909.github.io/tacticalrmm/"

dev_addr: "0.0.0.0:8005"

# Repository
repo_name: "wh1te909/tacticalrmm"
repo_url: "https://github.com/wh1te909/tacticalrmm"
edit_uri: ""

theme:
  name: "material"
  logo: "images/onit.ico"
  favicon: "images/favicon.ico"
  language: "en"
  palette:
    primary: "white"
    accent: "indigo"
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/wh1te909/tacticalrmm"
markdown_extensions:
  - pymdownx.inlinehilite
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
